// This file has been autogenerated from parsing an Objective-C header file added in Xcode.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace FieldService.iOS
{
	public partial class LaborCell : UITableViewCell
	{
		public LaborCell (IntPtr handle) : base (handle)
		{
		}
	}
}
