// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace EmployeeDirectory.Android
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_btn_search = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_menu_search = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_menu_search_holo_dark = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_menu_search_holo_light = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_menu_star = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_search = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_search_api_holo_light = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Icon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Placeholder = 2130837512;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070006
			public const int DetailsTextView = 2131165190;
			
			// aapt resource value: 0x7f070008
			public const int Divider = 2131165192;
			
			// aapt resource value: 0x7f070000
			public const int HeaderTextView = 2131165184;
			
			// aapt resource value: 0x7f070007
			public const int ImageButton = 2131165191;
			
			// aapt resource value: 0x7f07000b
			public const int MenuSearch = 2131165195;
			
			// aapt resource value: 0x7f070005
			public const int NameTextView = 2131165189;
			
			// aapt resource value: 0x7f07000a
			public const int emptyTextView = 2131165194;
			
			// aapt resource value: 0x7f070003
			public const int linearLayout1 = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int linearLayout2 = 2131165188;
			
			// aapt resource value: 0x7f070009
			public const int progressBar1 = 2131165193;
			
			// aapt resource value: 0x7f070002
			public const int textView1 = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int view1 = 2131165185;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int GroupHeaderListItem = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int MainActivity = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int PersonActivity = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int PersonListItem = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int SearchActivity = 2130903044;
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int AppActivityOptionsMenu = 2131099648;
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050002
			public const int FavoritesTabTitle = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int MenuSearch = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int NoFavoritesText = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int NoSearchResultsText = 2131034119;
			
			// aapt resource value: 0x7f050004
			public const int SearchHint = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int SearchTabTitle = 2131034113;
			
			// aapt resource value: 0x7f050006
			public const int SearchingText = 2131034118;
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			private String()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int searchable = 2130968576;
			
			private Xml()
			{
			}
		}
	}
}
