//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FieldService.Android
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int actionbar = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int loginbox = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int XamarinTitle = 2130837507;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int actionBar = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int actionBarTitle = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int dialogImage = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int dialogLayout = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int dialogTitle = 2131099652;
			
			// aapt resource value: 0x7f060007
			public const int logIn = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int password = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int userName = 2131099653;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int Password = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int Username = 2130968578;
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050001
			public const int CustomHoloTheme = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int LoginDialog = 2131034112;
			
			private Style()
			{
			}
		}
	}
}
