//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FieldService.Android
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040006
			public const int assignmentblue = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int assignmentgrey = 2130968583;
			
			// aapt resource value: 0x7f040005
			public const int assignmentoffwhite = 2130968581;
			
			// aapt resource value: 0x7f040001
			public const int blueassignmentbutton = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int blueclick = 2130968576;
			
			// aapt resource value: 0x7f04000a
			public const int confirmationborder = 2130968586;
			
			// aapt resource value: 0x7f04000c
			public const int disabledText = 2130968588;
			
			// aapt resource value: 0x7f040002
			public const int greybutton = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int greyheadertext = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int greyspinnertext = 2130968579;
			
			// aapt resource value: 0x7f040009
			public const int itemssearchcolor = 2130968585;
			
			// aapt resource value: 0x7f04000b
			public const int listviewdivider = 2130968587;
			
			// aapt resource value: 0x7f040008
			public const int navigationitemselected = 2130968584;
			
			// aapt resource value: 0x7f04000d
			public const int radio_selector_color = 2130968589;
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int accept = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int accept_assignment = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int AcceptedAssignmentIcon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int actionbar = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int active_assignment_selector = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ActiveAssignmentIcon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int assignment_list_selector = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int back_button = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int border = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int bottomSearchBar = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int cameraIcon = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int cancel_button = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int check_box = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int CheckBox = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int CheckBoxChecked = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int clear_search_button = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int clearIcon = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int clearIconDown = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int darkPhoneIcon = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int decline = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int decline_assignment = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int documentIcon = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int downlaborhours = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int EnrouteImage = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int get_directions_button = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int HoldImage = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int Icon = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int ItemPopupDivider = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int items_selector = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int labordescriptionbottom = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int laborHoursBottom = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int LaborHoursDivider = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int login_button = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int loginbox = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int MapIcon = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int MapOverlayDirections = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int MapOverlayDirectionsDown = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int MapOverlayDivider = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int MapOverlayIcon = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int navigation_selector = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int navigationIcon = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int NewAssignmentIcon = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int NextButton = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int PhoneIcon = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int PreviousButton = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int roundedblack = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int SearchIcon = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int SelectedItem = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int smallBlueRectangle = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int summary_timer = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int SummaryPause = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int SummaryRecord = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int tab_selected = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int tab_selector = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int tab_unselected = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int timer_selector = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int TimerPause = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int TimerRecord = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int TrashCanIcon = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int triangleblue = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int triangledark = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int trianglegrey = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int trianglewhite = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int UpLaborHours = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int XamarinTitle = 2130837568;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070034
			public const int actionBar = 2131165236;
			
			// aapt resource value: 0x7f070035
			public const int actionBarTitle = 2131165237;
			
			// aapt resource value: 0x7f070004
			public const int addExpenseAddPhoto = 2131165188;
			
			// aapt resource value: 0x7f070001
			public const int addExpenseAmount = 2131165185;
			
			// aapt resource value: 0x7f070006
			public const int addExpenseCancel = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int addExpenseDelete = 2131165191;
			
			// aapt resource value: 0x7f070002
			public const int addExpenseDescription = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int addExpenseImage = 2131165187;
			
			// aapt resource value: 0x7f070008
			public const int addExpenseSave = 2131165192;
			
			// aapt resource value: 0x7f070000
			public const int addExpenseType = 2131165184;
			
			// aapt resource value: 0x7f07000d
			public const int addLaborDescription = 2131165197;
			
			// aapt resource value: 0x7f07000b
			public const int addLaborHours = 2131165195;
			
			// aapt resource value: 0x7f07000a
			public const int addLaborHoursText = 2131165194;
			
			// aapt resource value: 0x7f070009
			public const int addLaborHoursType = 2131165193;
			
			// aapt resource value: 0x7f070030
			public const int assignmentAccept = 2131165232;
			
			// aapt resource value: 0x7f070028
			public const int assignmentAddress = 2131165224;
			
			// aapt resource value: 0x7f070026
			public const int assignmentAddressLayout = 2131165222;
			
			// aapt resource value: 0x7f07002f
			public const int assignmentButtonLayout = 2131165231;
			
			// aapt resource value: 0x7f070031
			public const int assignmentDecline = 2131165233;
			
			// aapt resource value: 0x7f070020
			public const int assignmentItemNumber = 2131165216;
			
			// aapt resource value: 0x7f070021
			public const int assignmentJob = 2131165217;
			
			// aapt resource value: 0x7f070027
			public const int assignmentMapIcon = 2131165223;
			
			// aapt resource value: 0x7f070022
			public const int assignmentName = 2131165218;
			
			// aapt resource value: 0x7f070025
			public const int assignmentPhone = 2131165221;
			
			// aapt resource value: 0x7f070024
			public const int assignmentPhoneIcon = 2131165220;
			
			// aapt resource value: 0x7f070023
			public const int assignmentPhoneLayout = 2131165219;
			
			// aapt resource value: 0x7f070032
			public const int assignmentSelectedItem = 2131165234;
			
			// aapt resource value: 0x7f07002e
			public const int assignmentStatus = 2131165230;
			
			// aapt resource value: 0x7f07002d
			public const int assignmentStatusImage = 2131165229;
			
			// aapt resource value: 0x7f07002c
			public const int assignmentTimer = 2131165228;
			
			// aapt resource value: 0x7f070029
			public const int assignmentTimerLayout = 2131165225;
			
			// aapt resource value: 0x7f07002b
			public const int assignmentTimerText = 2131165227;
			
			// aapt resource value: 0x7f070033
			public const int assignmentsListView = 2131165235;
			
			// aapt resource value: 0x7f070036
			public const int assingmentTabHost = 2131165238;
			
			// aapt resource value: 0x7f070080
			public const int backSummary = 2131165312;
			
			// aapt resource value: 0x7f07000e
			public const int cancelAddLabor = 2131165198;
			
			// aapt resource value: 0x7f070037
			public const int confirmationPhotoList = 2131165239;
			
			// aapt resource value: 0x7f070038
			public const int confirmationsAddPhoto = 2131165240;
			
			// aapt resource value: 0x7f07003a
			public const int confirmationsAddSignature = 2131165242;
			
			// aapt resource value: 0x7f07003b
			public const int confirmationsComplete = 2131165243;
			
			// aapt resource value: 0x7f070039
			public const int confirmationsSignature = 2131165241;
			
			// aapt resource value: 0x7f07008b
			public const int contentFrame = 2131165323;
			
			// aapt resource value: 0x7f07000f
			public const int deleteAddLabor = 2131165199;
			
			// aapt resource value: 0x7f070068
			public const int dialogImage = 2131165288;
			
			// aapt resource value: 0x7f070067
			public const int dialogLayout = 2131165287;
			
			// aapt resource value: 0x7f070069
			public const int dialogTitle = 2131165289;
			
			// aapt resource value: 0x7f07003f
			public const int documentListItemDocTitle = 2131165247;
			
			// aapt resource value: 0x7f07003e
			public const int documentListItemDocType = 2131165246;
			
			// aapt resource value: 0x7f07003d
			public const int documentListItemIcon = 2131165245;
			
			// aapt resource value: 0x7f07003c
			public const int documentsListView = 2131165244;
			
			// aapt resource value: 0x7f070041
			public const int expenseDescription = 2131165249;
			
			// aapt resource value: 0x7f070045
			public const int expenseListView = 2131165253;
			
			// aapt resource value: 0x7f070044
			public const int expensePhotoIcon = 2131165252;
			
			// aapt resource value: 0x7f070043
			public const int expenseText = 2131165251;
			
			// aapt resource value: 0x7f070040
			public const int expenseType = 2131165248;
			
			// aapt resource value: 0x7f070078
			public const int fragmentHours = 2131165304;
			
			// aapt resource value: 0x7f07006e
			public const int fragmentMapView = 2131165294;
			
			// aapt resource value: 0x7f070076
			public const int fragmentStatus = 2131165302;
			
			// aapt resource value: 0x7f070075
			public const int fragmentStatusImage = 2131165301;
			
			// aapt resource value: 0x7f070079
			public const int fragmentTimer = 2131165305;
			
			// aapt resource value: 0x7f070077
			public const int fragmentTimerTextLayout = 2131165303;
			
			// aapt resource value: 0x7f070073
			public const int googleMapsView = 2131165299;
			
			// aapt resource value: 0x7f07004a
			public const int historyClearSearch = 2131165258;
			
			// aapt resource value: 0x7f070052
			public const int historyItemAddress = 2131165266;
			
			// aapt resource value: 0x7f07004e
			public const int historyItemDate = 2131165262;
			
			// aapt resource value: 0x7f07004d
			public const int historyItemJobNumber = 2131165261;
			
			// aapt resource value: 0x7f07004f
			public const int historyItemJobTitle = 2131165263;
			
			// aapt resource value: 0x7f070051
			public const int historyItemMapImage = 2131165265;
			
			// aapt resource value: 0x7f07004c
			public const int historyItemPhoneImage = 2131165260;
			
			// aapt resource value: 0x7f070050
			public const int historyItemPhoneNumber = 2131165264;
			
			// aapt resource value: 0x7f07001f
			public const int historyListView = 2131165215;
			
			// aapt resource value: 0x7f070049
			public const int historySearchBar = 2131165257;
			
			// aapt resource value: 0x7f070047
			public const int historySearchLayout = 2131165255;
			
			// aapt resource value: 0x7f070048
			public const int historySearchText = 2131165256;
			
			// aapt resource value: 0x7f07004b
			public const int historyTabBottomDivider = 2131165259;
			
			// aapt resource value: 0x7f070046
			public const int historyTabHost = 2131165254;
			
			// aapt resource value: 0x7f070053
			public const int historyTabsLayout = 2131165267;
			
			// aapt resource value: 0x7f07008d
			public const int imageView1 = 2131165325;
			
			// aapt resource value: 0x7f07008e
			public const int imageView2 = 2131165326;
			
			// aapt resource value: 0x7f070055
			public const int itemCheckBox = 2131165269;
			
			// aapt resource value: 0x7f070056
			public const int itemName = 2131165270;
			
			// aapt resource value: 0x7f070061
			public const int itemPopupItemsList = 2131165281;
			
			// aapt resource value: 0x7f070057
			public const int itemTrashButton = 2131165271;
			
			// aapt resource value: 0x7f070058
			public const int itemsListItemText = 2131165272;
			
			// aapt resource value: 0x7f070059
			public const int itemsListViewFragment = 2131165273;
			
			// aapt resource value: 0x7f070062
			public const int itemsPopupCancelButton = 2131165282;
			
			// aapt resource value: 0x7f070060
			public const int itemsPopupDivider = 2131165280;
			
			// aapt resource value: 0x7f07005b
			public const int itemsPopupHeader = 2131165275;
			
			// aapt resource value: 0x7f07005f
			public const int itemsPopupSeachClear = 2131165279;
			
			// aapt resource value: 0x7f07005d
			public const int itemsPopupSearchImage = 2131165277;
			
			// aapt resource value: 0x7f07005e
			public const int itemsPopupSearchText = 2131165278;
			
			// aapt resource value: 0x7f07005a
			public const int itemsSearchTopLinearLayout = 2131165274;
			
			// aapt resource value: 0x7f070065
			public const int laborDescription = 2131165285;
			
			// aapt resource value: 0x7f070066
			public const int laborHours = 2131165286;
			
			// aapt resource value: 0x7f070063
			public const int laborListViewFragment = 2131165283;
			
			// aapt resource value: 0x7f070064
			public const int laborType = 2131165284;
			
			// aapt resource value: 0x7f070005
			public const int linearLayout1 = 2131165189;
			
			// aapt resource value: 0x7f070018
			public const int linearLayout2 = 2131165208;
			
			// aapt resource value: 0x7f07006c
			public const int logIn = 2131165292;
			
			// aapt resource value: 0x7f07006d
			public const int loginProgress = 2131165293;
			
			// aapt resource value: 0x7f070071
			public const int mapOverlayAddress = 2131165297;
			
			// aapt resource value: 0x7f070070
			public const int mapOverlayDivider = 2131165296;
			
			// aapt resource value: 0x7f07006f
			public const int mapOverlayGetDirections = 2131165295;
			
			// aapt resource value: 0x7f070072
			public const int mapViewAssignmentLayout = 2131165298;
			
			// aapt resource value: 0x7f070081
			public const int navigationFragmentContainer = 2131165313;
			
			// aapt resource value: 0x7f070074
			public const int navigationListView = 2131165300;
			
			// aapt resource value: 0x7f07007b
			public const int navigationListViewImage = 2131165307;
			
			// aapt resource value: 0x7f07007a
			public const int navigationListViewText = 2131165306;
			
			// aapt resource value: 0x7f07008f
			public const int navigationMenu = 2131165327;
			
			// aapt resource value: 0x7f07006b
			public const int password = 2131165291;
			
			// aapt resource value: 0x7f070019
			public const int photoCancelImage = 2131165209;
			
			// aapt resource value: 0x7f070016
			public const int photoCountText = 2131165206;
			
			// aapt resource value: 0x7f070012
			public const int photoDateTime = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int photoDeleteImage = 2131165203;
			
			// aapt resource value: 0x7f07001a
			public const int photoDoneImage = 2131165210;
			
			// aapt resource value: 0x7f070014
			public const int photoImageSource = 2131165204;
			
			// aapt resource value: 0x7f07007d
			public const int photoListViewDateTime = 2131165309;
			
			// aapt resource value: 0x7f07007e
			public const int photoListViewDescription = 2131165310;
			
			// aapt resource value: 0x7f07007c
			public const int photoListViewImage = 2131165308;
			
			// aapt resource value: 0x7f070017
			public const int photoNextButton = 2131165207;
			
			// aapt resource value: 0x7f070011
			public const int photoPopupDescription = 2131165201;
			
			// aapt resource value: 0x7f070015
			public const int photoPreviousButton = 2131165205;
			
			// aapt resource value: 0x7f07005c
			public const int relativeLayout1 = 2131165276;
			
			// aapt resource value: 0x7f070010
			public const int saveAddLabor = 2131165200;
			
			// aapt resource value: 0x7f070082
			public const int selectedAssignment = 2131165314;
			
			// aapt resource value: 0x7f07008a
			public const int selectedAssignmentAddExpense = 2131165322;
			
			// aapt resource value: 0x7f070089
			public const int selectedAssignmentAddItem = 2131165321;
			
			// aapt resource value: 0x7f070088
			public const int selectedAssignmentAddLabor = 2131165320;
			
			// aapt resource value: 0x7f070086
			public const int selectedAssignmentAddress = 2131165318;
			
			// aapt resource value: 0x7f070084
			public const int selectedAssignmentContactName = 2131165316;
			
			// aapt resource value: 0x7f070083
			public const int selectedAssignmentNumber = 2131165315;
			
			// aapt resource value: 0x7f070085
			public const int selectedAssignmentPhoneNumber = 2131165317;
			
			// aapt resource value: 0x7f070087
			public const int selectedAssignmentTotalItems = 2131165319;
			
			// aapt resource value: 0x7f07001d
			public const int signatureCancelButton = 2131165213;
			
			// aapt resource value: 0x7f07001c
			public const int signatureImage = 2131165212;
			
			// aapt resource value: 0x7f07001e
			public const int signatureSaveButton = 2131165214;
			
			// aapt resource value: 0x7f07007f
			public const int simpleSpinnerTextView = 2131165311;
			
			// aapt resource value: 0x7f07000c
			public const int subtractLaborHours = 2131165196;
			
			// aapt resource value: 0x7f070091
			public const int summaryAssignmentDescription = 2131165329;
			
			// aapt resource value: 0x7f070090
			public const int summaryAssignmentDescriptionHeader = 2131165328;
			
			// aapt resource value: 0x7f070094
			public const int summaryAssignmentExpenses = 2131165332;
			
			// aapt resource value: 0x7f070092
			public const int summaryAssignmentItems = 2131165330;
			
			// aapt resource value: 0x7f070093
			public const int summaryAssignmentLaborHours = 2131165331;
			
			// aapt resource value: 0x7f07008c
			public const int summaryAssignmentTitle = 2131165324;
			
			// aapt resource value: 0x7f070054
			public const int tabsText = 2131165268;
			
			// aapt resource value: 0x7f07001b
			public const int textView1 = 2131165211;
			
			// aapt resource value: 0x7f070042
			public const int textView2 = 2131165250;
			
			// aapt resource value: 0x7f07002a
			public const int timerLinearLayout = 2131165226;
			
			// aapt resource value: 0x7f07006a
			public const int userName = 2131165290;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddExpensePopUpLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AddLaborPopUpLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int AddPhotoPopUpLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int AddSignatureLayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int AssignmentHistoryLayout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int AssignmentItemLayout = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int AssignmentsLayout = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int AssignmentsTabsLayout = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int ConfirmationsLayout = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int DocumentFragmentLayout = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int DocumentListItemLayout = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int ExpenseListItemLayout = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int ExpensesFragmentLayout = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int HistoryFragmentLayout = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int HistoryItemLayout = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int HistoryTabs = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int ItemLayout = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int ItemSearchListItemLayout = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int ItemsFragmentLayout = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int ItemsPopUpLayout = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int LaborHoursLayout = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int LaborHoursListItemLayout = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int LoginLayout = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int MapFragmentLayout = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int MapOverlayLayout = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int MapViewLayout = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int NavigationLayout = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int NavigationListItemLayout = 2130903067;
			
			// aapt resource value: 0x7f03001c
			public const int PhotoItemLayout = 2130903068;
			
			// aapt resource value: 0x7f03001d
			public const int SimpleSpinnerItem = 2130903069;
			
			// aapt resource value: 0x7f03001e
			public const int SummaryFragmentLayout = 2130903070;
			
			// aapt resource value: 0x7f03001f
			public const int SummaryLayout = 2130903071;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050006
			public const int Accept = 2131034118;
			
			// aapt resource value: 0x7f05001d
			public const int AddExpense = 2131034141;
			
			// aapt resource value: 0x7f05001c
			public const int AddItem = 2131034140;
			
			// aapt resource value: 0x7f05000c
			public const int AddLabor = 2131034124;
			
			// aapt resource value: 0x7f050013
			public const int AddPhoto = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int AddSignature = 2131034132;
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f05001a
			public const int Camera = 2131034138;
			
			// aapt resource value: 0x7f05000e
			public const int Cancel = 2131034126;
			
			// aapt resource value: 0x7f050019
			public const int Clear = 2131034137;
			
			// aapt resource value: 0x7f050015
			public const int Complete = 2131034133;
			
			// aapt resource value: 0x7f050007
			public const int Decline = 2131034119;
			
			// aapt resource value: 0x7f05000f
			public const int Delete = 2131034127;
			
			// aapt resource value: 0x7f050016
			public const int DeletePhoto = 2131034134;
			
			// aapt resource value: 0x7f05001e
			public const int DollarSign = 2131034142;
			
			// aapt resource value: 0x7f050017
			public const int Done = 2131034135;
			
			// aapt resource value: 0x7f050009
			public const int Expenses = 2131034121;
			
			// aapt resource value: 0x7f05001b
			public const int Gallery = 2131034139;
			
			// aapt resource value: 0x7f050020
			public const int GoogleMapsAPIKey = 2131034144;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f05000d
			public const int HoursAbbrev = 2131034125;
			
			// aapt resource value: 0x7f05000a
			public const int Items = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int LaborHours = 2131034123;
			
			// aapt resource value: 0x7f050005
			public const int MapTab = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int Password = 2131034115;
			
			// aapt resource value: 0x7f050011
			public const int Photos = 2131034129;
			
			// aapt resource value: 0x7f050018
			public const int PleaseSign = 2131034136;
			
			// aapt resource value: 0x7f050004
			public const int PriorityTab = 2131034116;
			
			// aapt resource value: 0x7f050010
			public const int Save = 2131034128;
			
			// aapt resource value: 0x7f05001f
			public const int Search = 2131034143;
			
			// aapt resource value: 0x7f050012
			public const int Signature = 2131034130;
			
			// aapt resource value: 0x7f050002
			public const int Username = 2131034114;
			
			// aapt resource value: 0x7f050008
			public const int Xamarin = 2131034120;
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060001
			public const int CustomDialogTheme = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int CustomHoloTheme = 2131099648;
			
			private Style()
			{
			}
		}
	}
}
