//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FieldService.Android
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040006
			public const int assignmentblue = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int assignmentgrey = 2130968583;
			
			// aapt resource value: 0x7f040005
			public const int assignmentoffwhite = 2130968581;
			
			// aapt resource value: 0x7f040001
			public const int blueassignmentbutton = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int blueclick = 2130968576;
			
			// aapt resource value: 0x7f04000a
			public const int confirmationborder = 2130968586;
			
			// aapt resource value: 0x7f04000c
			public const int disabledText = 2130968588;
			
			// aapt resource value: 0x7f040002
			public const int greybutton = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int greyheadertext = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int greyspinnertext = 2130968579;
			
			// aapt resource value: 0x7f040009
			public const int itemssearchcolor = 2130968585;
			
			// aapt resource value: 0x7f04000b
			public const int listviewdivider = 2130968587;
			
			// aapt resource value: 0x7f040008
			public const int navigationitemselected = 2130968584;
			
			// aapt resource value: 0x7f04000d
			public const int radio_selector_color = 2130968589;
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int accept = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int accept_assignment = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int AcceptedAssignmentIcon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int action_bar_back = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int actionbar = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int active_assignment_selector = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ActiveAssignmentIcon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int assignment_list_selector = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int back_button = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int border = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int bottomSearchBar = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int cameraIcon = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int cancel_button = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int clear_search_button = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int clearIcon = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int clearIconDown = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int darkPhoneIcon = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int decline = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int decline_assignment = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int documentIcon = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int downlaborhours = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int EnrouteImage = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int get_directions_button = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int HoldImage = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int Icon = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int ItemPopupDivider = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int items_selector = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int labordescriptionbottom = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int laborHoursBottom = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int LaborHoursDivider = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int login_button = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int loginbox = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int MapIcon = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int mapOverlay = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int MapOverlayDirections = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int MapOverlayDirectionsDown = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int MapOverlayDivider = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int MapOverlayIcon = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int MapOverlayIconDown = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int navigation_selector = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int navigationIcon = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int NewAssignmentIcon = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int NextButton = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int PhoneIcon = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int PreviousButton = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int roundedblack = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int SearchIcon = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int SelectedItem = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int smallBlueRectangle = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int summary_timer = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int SummaryPause = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int SummaryRecord = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int tab_selected = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int tab_selector = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int tab_unselected = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int timer_selector = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int TimerPause = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int TimerRecord = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int TrashCanIcon = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int triangleblue = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int triangledark = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int trianglegrey = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int trianglewhite = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int UpLaborHours = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int XamarinTitle = 2130837568;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080034
			public const int actionBar = 2131230772;
			
			// aapt resource value: 0x7f080035
			public const int actionBarTitle = 2131230773;
			
			// aapt resource value: 0x7f080005
			public const int addExpenseAddPhoto = 2131230725;
			
			// aapt resource value: 0x7f080001
			public const int addExpenseAmount = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int addExpenseAmountBottom = 2131230722;
			
			// aapt resource value: 0x7f080007
			public const int addExpenseCancel = 2131230727;
			
			// aapt resource value: 0x7f080008
			public const int addExpenseDelete = 2131230728;
			
			// aapt resource value: 0x7f080003
			public const int addExpenseDescription = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int addExpenseImage = 2131230724;
			
			// aapt resource value: 0x7f080009
			public const int addExpenseSave = 2131230729;
			
			// aapt resource value: 0x7f080000
			public const int addExpenseType = 2131230720;
			
			// aapt resource value: 0x7f08000e
			public const int addLaborDescription = 2131230734;
			
			// aapt resource value: 0x7f08000c
			public const int addLaborHours = 2131230732;
			
			// aapt resource value: 0x7f08000b
			public const int addLaborHoursText = 2131230731;
			
			// aapt resource value: 0x7f08000a
			public const int addLaborHoursType = 2131230730;
			
			// aapt resource value: 0x7f080030
			public const int assignmentAccept = 2131230768;
			
			// aapt resource value: 0x7f080028
			public const int assignmentAddress = 2131230760;
			
			// aapt resource value: 0x7f080026
			public const int assignmentAddressLayout = 2131230758;
			
			// aapt resource value: 0x7f08002f
			public const int assignmentButtonLayout = 2131230767;
			
			// aapt resource value: 0x7f080031
			public const int assignmentDecline = 2131230769;
			
			// aapt resource value: 0x7f080020
			public const int assignmentItemNumber = 2131230752;
			
			// aapt resource value: 0x7f080021
			public const int assignmentJob = 2131230753;
			
			// aapt resource value: 0x7f080027
			public const int assignmentMapIcon = 2131230759;
			
			// aapt resource value: 0x7f080022
			public const int assignmentName = 2131230754;
			
			// aapt resource value: 0x7f080025
			public const int assignmentPhone = 2131230757;
			
			// aapt resource value: 0x7f080024
			public const int assignmentPhoneIcon = 2131230756;
			
			// aapt resource value: 0x7f080023
			public const int assignmentPhoneLayout = 2131230755;
			
			// aapt resource value: 0x7f080032
			public const int assignmentSelectedItem = 2131230770;
			
			// aapt resource value: 0x7f08002e
			public const int assignmentStatus = 2131230766;
			
			// aapt resource value: 0x7f08002d
			public const int assignmentStatusImage = 2131230765;
			
			// aapt resource value: 0x7f08002c
			public const int assignmentTimer = 2131230764;
			
			// aapt resource value: 0x7f080029
			public const int assignmentTimerLayout = 2131230761;
			
			// aapt resource value: 0x7f08002b
			public const int assignmentTimerText = 2131230763;
			
			// aapt resource value: 0x7f080033
			public const int assignmentsListView = 2131230771;
			
			// aapt resource value: 0x7f080036
			public const int assingmentTabHost = 2131230774;
			
			// aapt resource value: 0x7f08000f
			public const int cancelAddLabor = 2131230735;
			
			// aapt resource value: 0x7f080037
			public const int confirmationPhotoList = 2131230775;
			
			// aapt resource value: 0x7f080038
			public const int confirmationsAddPhoto = 2131230776;
			
			// aapt resource value: 0x7f08003a
			public const int confirmationsAddSignature = 2131230778;
			
			// aapt resource value: 0x7f08003b
			public const int confirmationsComplete = 2131230779;
			
			// aapt resource value: 0x7f080039
			public const int confirmationsSignature = 2131230777;
			
			// aapt resource value: 0x7f08008f
			public const int contentFrame = 2131230863;
			
			// aapt resource value: 0x7f080010
			public const int deleteAddLabor = 2131230736;
			
			// aapt resource value: 0x7f080068
			public const int dialogImage = 2131230824;
			
			// aapt resource value: 0x7f080067
			public const int dialogLayout = 2131230823;
			
			// aapt resource value: 0x7f080069
			public const int dialogTitle = 2131230825;
			
			// aapt resource value: 0x7f08003f
			public const int documentListItemDocTitle = 2131230783;
			
			// aapt resource value: 0x7f08003e
			public const int documentListItemDocType = 2131230782;
			
			// aapt resource value: 0x7f08003d
			public const int documentListItemIcon = 2131230781;
			
			// aapt resource value: 0x7f08003c
			public const int documentsListView = 2131230780;
			
			// aapt resource value: 0x7f080044
			public const int expenseAmountBottom = 2131230788;
			
			// aapt resource value: 0x7f080041
			public const int expenseDescription = 2131230785;
			
			// aapt resource value: 0x7f080046
			public const int expenseListView = 2131230790;
			
			// aapt resource value: 0x7f080045
			public const int expensePhotoIcon = 2131230789;
			
			// aapt resource value: 0x7f080043
			public const int expenseText = 2131230787;
			
			// aapt resource value: 0x7f080040
			public const int expenseType = 2131230784;
			
			// aapt resource value: 0x7f080079
			public const int fragmentHours = 2131230841;
			
			// aapt resource value: 0x7f08006e
			public const int fragmentMapView = 2131230830;
			
			// aapt resource value: 0x7f080077
			public const int fragmentStatus = 2131230839;
			
			// aapt resource value: 0x7f080076
			public const int fragmentStatusImage = 2131230838;
			
			// aapt resource value: 0x7f08007a
			public const int fragmentTimer = 2131230842;
			
			// aapt resource value: 0x7f080078
			public const int fragmentTimerTextLayout = 2131230840;
			
			// aapt resource value: 0x7f080074
			public const int googleMapsView = 2131230836;
			
			// aapt resource value: 0x7f08004b
			public const int historyClearSearch = 2131230795;
			
			// aapt resource value: 0x7f080053
			public const int historyItemAddress = 2131230803;
			
			// aapt resource value: 0x7f08004f
			public const int historyItemDate = 2131230799;
			
			// aapt resource value: 0x7f08004e
			public const int historyItemJobNumber = 2131230798;
			
			// aapt resource value: 0x7f080050
			public const int historyItemJobTitle = 2131230800;
			
			// aapt resource value: 0x7f080052
			public const int historyItemMapImage = 2131230802;
			
			// aapt resource value: 0x7f08004d
			public const int historyItemPhoneImage = 2131230797;
			
			// aapt resource value: 0x7f080051
			public const int historyItemPhoneNumber = 2131230801;
			
			// aapt resource value: 0x7f08001f
			public const int historyListView = 2131230751;
			
			// aapt resource value: 0x7f08004a
			public const int historySearchBar = 2131230794;
			
			// aapt resource value: 0x7f080048
			public const int historySearchLayout = 2131230792;
			
			// aapt resource value: 0x7f080049
			public const int historySearchText = 2131230793;
			
			// aapt resource value: 0x7f08004c
			public const int historyTabBottomDivider = 2131230796;
			
			// aapt resource value: 0x7f080047
			public const int historyTabHost = 2131230791;
			
			// aapt resource value: 0x7f080054
			public const int historyTabsLayout = 2131230804;
			
			// aapt resource value: 0x7f080056
			public const int itemName = 2131230806;
			
			// aapt resource value: 0x7f080061
			public const int itemPopupItemsList = 2131230817;
			
			// aapt resource value: 0x7f080057
			public const int itemTrashButton = 2131230807;
			
			// aapt resource value: 0x7f080058
			public const int itemsListItemText = 2131230808;
			
			// aapt resource value: 0x7f080059
			public const int itemsListViewFragment = 2131230809;
			
			// aapt resource value: 0x7f080062
			public const int itemsPopupCancelButton = 2131230818;
			
			// aapt resource value: 0x7f080060
			public const int itemsPopupDivider = 2131230816;
			
			// aapt resource value: 0x7f08005b
			public const int itemsPopupHeader = 2131230811;
			
			// aapt resource value: 0x7f08005f
			public const int itemsPopupSeachClear = 2131230815;
			
			// aapt resource value: 0x7f08005d
			public const int itemsPopupSearchImage = 2131230813;
			
			// aapt resource value: 0x7f08005e
			public const int itemsPopupSearchText = 2131230814;
			
			// aapt resource value: 0x7f08005a
			public const int itemsSearchTopLinearLayout = 2131230810;
			
			// aapt resource value: 0x7f080065
			public const int laborDescription = 2131230821;
			
			// aapt resource value: 0x7f080066
			public const int laborHours = 2131230822;
			
			// aapt resource value: 0x7f080063
			public const int laborListViewFragment = 2131230819;
			
			// aapt resource value: 0x7f080064
			public const int laborType = 2131230820;
			
			// aapt resource value: 0x7f080006
			public const int linearLayout1 = 2131230726;
			
			// aapt resource value: 0x7f080019
			public const int linearLayout2 = 2131230745;
			
			// aapt resource value: 0x7f08006c
			public const int logIn = 2131230828;
			
			// aapt resource value: 0x7f08006d
			public const int loginProgress = 2131230829;
			
			// aapt resource value: 0x7f080072
			public const int mapOverlayAddress = 2131230834;
			
			// aapt resource value: 0x7f080071
			public const int mapOverlayDivider = 2131230833;
			
			// aapt resource value: 0x7f080070
			public const int mapOverlayGetDirections = 2131230832;
			
			// aapt resource value: 0x7f080073
			public const int mapViewAssignmentLayout = 2131230835;
			
			// aapt resource value: 0x7f080082
			public const int navigationFragmentContainer = 2131230850;
			
			// aapt resource value: 0x7f080075
			public const int navigationListView = 2131230837;
			
			// aapt resource value: 0x7f08007c
			public const int navigationListViewImage = 2131230844;
			
			// aapt resource value: 0x7f08007b
			public const int navigationListViewText = 2131230843;
			
			// aapt resource value: 0x7f08009a
			public const int navigationMenu = 2131230874;
			
			// aapt resource value: 0x7f08007d
			public const int navigationMenuListView = 2131230845;
			
			// aapt resource value: 0x7f08006f
			public const int overlayDirectionsLayout = 2131230831;
			
			// aapt resource value: 0x7f08006b
			public const int password = 2131230827;
			
			// aapt resource value: 0x7f08001a
			public const int photoCancelImage = 2131230746;
			
			// aapt resource value: 0x7f080017
			public const int photoCountText = 2131230743;
			
			// aapt resource value: 0x7f080013
			public const int photoDateTime = 2131230739;
			
			// aapt resource value: 0x7f080014
			public const int photoDeleteImage = 2131230740;
			
			// aapt resource value: 0x7f08001b
			public const int photoDoneImage = 2131230747;
			
			// aapt resource value: 0x7f080015
			public const int photoImageSource = 2131230741;
			
			// aapt resource value: 0x7f08007f
			public const int photoListViewDateTime = 2131230847;
			
			// aapt resource value: 0x7f080080
			public const int photoListViewDescription = 2131230848;
			
			// aapt resource value: 0x7f08007e
			public const int photoListViewImage = 2131230846;
			
			// aapt resource value: 0x7f080018
			public const int photoNextButton = 2131230744;
			
			// aapt resource value: 0x7f080012
			public const int photoPopupDescription = 2131230738;
			
			// aapt resource value: 0x7f080016
			public const int photoPreviousButton = 2131230742;
			
			// aapt resource value: 0x7f08005c
			public const int relativeLayout1 = 2131230812;
			
			// aapt resource value: 0x7f080011
			public const int saveAddLabor = 2131230737;
			
			// aapt resource value: 0x7f080083
			public const int selectedAssignment = 2131230851;
			
			// aapt resource value: 0x7f08008e
			public const int selectedAssignmentAddExpense = 2131230862;
			
			// aapt resource value: 0x7f08008d
			public const int selectedAssignmentAddItem = 2131230861;
			
			// aapt resource value: 0x7f08008c
			public const int selectedAssignmentAddLabor = 2131230860;
			
			// aapt resource value: 0x7f08008a
			public const int selectedAssignmentAddress = 2131230858;
			
			// aapt resource value: 0x7f080085
			public const int selectedAssignmentContactName = 2131230853;
			
			// aapt resource value: 0x7f080084
			public const int selectedAssignmentNumber = 2131230852;
			
			// aapt resource value: 0x7f080088
			public const int selectedAssignmentPhoneNumber = 2131230856;
			
			// aapt resource value: 0x7f08008b
			public const int selectedAssignmentTotalItems = 2131230859;
			
			// aapt resource value: 0x7f08001d
			public const int signatureCancelButton = 2131230749;
			
			// aapt resource value: 0x7f08001c
			public const int signatureImage = 2131230748;
			
			// aapt resource value: 0x7f08001e
			public const int signatureSaveButton = 2131230750;
			
			// aapt resource value: 0x7f080081
			public const int simpleSpinnerTextView = 2131230849;
			
			// aapt resource value: 0x7f08000d
			public const int subtractLaborHours = 2131230733;
			
			// aapt resource value: 0x7f080092
			public const int summaryAssignmentDescription = 2131230866;
			
			// aapt resource value: 0x7f080091
			public const int summaryAssignmentDescriptionHeader = 2131230865;
			
			// aapt resource value: 0x7f080099
			public const int summaryAssignmentExpenses = 2131230873;
			
			// aapt resource value: 0x7f080095
			public const int summaryAssignmentItems = 2131230869;
			
			// aapt resource value: 0x7f080097
			public const int summaryAssignmentLaborHours = 2131230871;
			
			// aapt resource value: 0x7f080090
			public const int summaryAssignmentTitle = 2131230864;
			
			// aapt resource value: 0x7f080098
			public const int summaryExpensesLayout = 2131230872;
			
			// aapt resource value: 0x7f080087
			public const int summaryFragmentPhoneIcon = 2131230855;
			
			// aapt resource value: 0x7f080093
			public const int summaryItemsLayout = 2131230867;
			
			// aapt resource value: 0x7f080096
			public const int summaryLaborLayout = 2131230870;
			
			// aapt resource value: 0x7f080089
			public const int summaryMapIconLayout = 2131230857;
			
			// aapt resource value: 0x7f080086
			public const int summaryPhoneIconLayout = 2131230854;
			
			// aapt resource value: 0x7f080055
			public const int tabsText = 2131230805;
			
			// aapt resource value: 0x7f080094
			public const int textView1 = 2131230868;
			
			// aapt resource value: 0x7f080042
			public const int textView2 = 2131230786;
			
			// aapt resource value: 0x7f08002a
			public const int timerLinearLayout = 2131230762;
			
			// aapt resource value: 0x7f08006a
			public const int userName = 2131230826;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddExpensePopUpLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int AddLaborPopUpLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int AddPhotoPopUpLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int AddSignatureLayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int AssignmentHistoryLayout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int AssignmentItemLayout = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int AssignmentsLayout = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int AssignmentsTabsLayout = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int ConfirmationsLayout = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int DocumentFragmentLayout = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int DocumentListItemLayout = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int ExpenseListItemLayout = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int ExpensesFragmentLayout = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int HistoryFragmentLayout = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int HistoryItemLayout = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int HistoryTabs = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int ItemLayout = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int ItemSearchListItemLayout = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int ItemsFragmentLayout = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int ItemsPopUpLayout = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int LaborHoursLayout = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int LaborHoursListItemLayout = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int LoginLayout = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int MapFragmentLayout = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int MapOverlayLayout = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int MapViewLayout = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int NavigationLayout = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int NavigationListItemLayout = 2130903067;
			
			// aapt resource value: 0x7f03001c
			public const int NavigationMenu = 2130903068;
			
			// aapt resource value: 0x7f03001d
			public const int PhotoItemLayout = 2130903069;
			
			// aapt resource value: 0x7f03001e
			public const int SimpleSpinnerItem = 2130903070;
			
			// aapt resource value: 0x7f03001f
			public const int SummaryFragmentLayout = 2130903071;
			
			// aapt resource value: 0x7f030020
			public const int SummaryLayout = 2130903072;
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int SummaryMenu = 2131165184;
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050006
			public const int Accept = 2131034118;
			
			// aapt resource value: 0x7f05001e
			public const int AddExpense = 2131034142;
			
			// aapt resource value: 0x7f05001d
			public const int AddItem = 2131034141;
			
			// aapt resource value: 0x7f05000c
			public const int AddLabor = 2131034124;
			
			// aapt resource value: 0x7f050014
			public const int AddPhoto = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int AddSignature = 2131034133;
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f05001b
			public const int Camera = 2131034139;
			
			// aapt resource value: 0x7f05000e
			public const int Cancel = 2131034126;
			
			// aapt resource value: 0x7f05001a
			public const int Clear = 2131034138;
			
			// aapt resource value: 0x7f050016
			public const int Complete = 2131034134;
			
			// aapt resource value: 0x7f050028
			public const int Confirmations = 2131034152;
			
			// aapt resource value: 0x7f050007
			public const int Decline = 2131034119;
			
			// aapt resource value: 0x7f05000f
			public const int Delete = 2131034127;
			
			// aapt resource value: 0x7f050017
			public const int DeletePhoto = 2131034135;
			
			// aapt resource value: 0x7f050027
			public const int Documents = 2131034151;
			
			// aapt resource value: 0x7f05001f
			public const int DollarSign = 2131034143;
			
			// aapt resource value: 0x7f050018
			public const int Done = 2131034136;
			
			// aapt resource value: 0x7f050022
			public const int EnterDescription = 2131034146;
			
			// aapt resource value: 0x7f050009
			public const int Expenses = 2131034121;
			
			// aapt resource value: 0x7f05001c
			public const int Gallery = 2131034140;
			
			// aapt resource value: 0x7f050021
			public const int GoogleMapsAPIKey = 2131034145;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050026
			public const int History = 2131034150;
			
			// aapt resource value: 0x7f05000d
			public const int HoursAbbrev = 2131034125;
			
			// aapt resource value: 0x7f05000a
			public const int Items = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int LaborHours = 2131034123;
			
			// aapt resource value: 0x7f050025
			public const int Map = 2131034149;
			
			// aapt resource value: 0x7f050005
			public const int MapTab = 2131034117;
			
			// aapt resource value: 0x7f050023
			public const int OptionalCaption = 2131034147;
			
			// aapt resource value: 0x7f050003
			public const int Password = 2131034115;
			
			// aapt resource value: 0x7f050012
			public const int Photo = 2131034130;
			
			// aapt resource value: 0x7f050011
			public const int Photos = 2131034129;
			
			// aapt resource value: 0x7f050019
			public const int PleaseSign = 2131034137;
			
			// aapt resource value: 0x7f050004
			public const int PriorityTab = 2131034116;
			
			// aapt resource value: 0x7f050010
			public const int Save = 2131034128;
			
			// aapt resource value: 0x7f050020
			public const int Search = 2131034144;
			
			// aapt resource value: 0x7f050013
			public const int Signature = 2131034131;
			
			// aapt resource value: 0x7f050024
			public const int Summary = 2131034148;
			
			// aapt resource value: 0x7f050002
			public const int Username = 2131034114;
			
			// aapt resource value: 0x7f050008
			public const int Xamarin = 2131034120;
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060001
			public const int CustomDialogTheme = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int CustomHoloTheme = 2131099648;
			
			private Style()
			{
			}
		}
	}
}
